// ui/src/main/webapp/src/app/shared/log-view/log-view.component.ts
import {Component, ChangeDetectionStrategy, Input} from "@angular/core";

@Component({
    templateUrl: './log-view.component.html',
    styleUrls: ['./log-view.component.scss'],
    selector: 'wu-log-view',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class LogViewComponent {
    private _text: string;

    @Input()
    lines: string[] = [ "Loading..." ];

    constructor() {

    }

    @Input()
    public set text(text: string) {
        if (!text) {
            text = '';
        }

        this._text = text;
        this.lines = text.split(/\r?\n/g);
    }
}

<div #logview class="log-view">
    <div class="log-scroll log-scroll-top target-logger-node" [ngClass]="{'affix': !isOnTop()}">
        <a (click)="toggleAutoScroll()" class="follow-links">
            <span *ngIf="!autoScrollActive">Follow</span>
            <span *ngIf="autoScrollActive">Stop following</span>
        </a>
    </div>
    <div class="log-view-output">
        <table>
            <tr *ngFor="let line of lines; let i = index" class="log-line">
                <td class="log-line-number">{{i + 1}}</td>
                <td class="log-line-text">{{line}}</td>
            </tr>
        </table>
    </div>
    <div class="log-scroll log-scroll-bottom">
        <a (click)="onScrollTop()" class="follow-links">Go to top</a>
    </div>
</div>

// ui-pf4/src/main/webapp/src/components/log-view/log-view.tsx
import * as React from "react";

import "./log-view.scss";

export interface LogViewProps {
  lines: string[];
}

export const LogView: React.FC<LogViewProps> = ({ lines }) => {
  return (
    <div className="log-view__component">
      <div className="log-view">
        {/* <div className="log-scroll log-scroll-top target-logger-node">
          <a className="follow-links">
            <span>Follow</span>
            <span>Stop following</span>
          </a>
        </div> */}
        <div className="log-view-output">
          <table>
            <tbody>
              {lines.map((line, i) => (
                <tr key={i} className="log-line">
                  <td className="log-line-number">{i}</td>
                  <td className="log-line-text">{line}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {/* <div className="log-scroll log-scroll-bottom">
          <a className="follow-links">Go to top</a>
        </div> */}
      </div>
    </div>
  );
};
